<?php

namespace ContainerUlVkX74;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O5hto6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O_5hto6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O_5hto6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'association' => ['privates', '.errored..service_locator.O_5hto6.App\\Entity\\Association', NULL, 'Cannot autowire service ".service_locator.O_5hto6": it references class "App\\Entity\\Association" but no such service exists.'],
            'associationEditFormType' => ['privates', 'App\\Form\\AssociationEditFormType', 'getAssociationEditFormTypeService', true],
            'associationRepository' => ['privates', 'App\\Repository\\AssociationRepository', 'getAssociationRepositoryService', true],
        ], [
            'association' => 'App\\Entity\\Association',
            'associationEditFormType' => 'App\\Form\\AssociationEditFormType',
            'associationRepository' => 'App\\Repository\\AssociationRepository',
        ]);
    }
}
