<?php

namespace ContainerUlVkX74;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssociationEditPAFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AssociationEditPAFormType' shared autowired service.
     *
     * @return \App\Form\AssociationEditPAFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AssociationEditPAFormType'] = new \App\Form\AssociationEditPAFormType(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
