<?php

namespace ContainerUlVkX74;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BaseController' shared autowired service.
     *
     * @return \App\Controller\BaseController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BaseController'] = $instance = new \App\Controller\BaseController();

        $instance->setContainer(($container->privates['.service_locator.vM_XwGp'] ?? $container->load('get_ServiceLocator_VMXwGpService'))->withContext('App\\Controller\\BaseController', $container));

        return $instance;
    }
}
