<?php

namespace ContainerUlVkX74;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoriqueRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\HistoriqueRepository' shared autowired service.
     *
     * @return \App\Repository\HistoriqueRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\HistoriqueRepository'] = new \App\Repository\HistoriqueRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
