<?php

namespace ContainerUlVkX74;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpportuniteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CEKAkqR.App\Entity\Opportunite' shared service.
     *
     * @return \App\Entity\Opportunite
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CEKAkqR": it references class "App\\Entity\\Opportunite" but no such service exists.');
    }
}
