<?php

namespace ContainerUlVkX74;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserInscritFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UserInscritFormType' shared autowired service.
     *
     * @return \App\Form\UserInscritFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\UserInscritFormType'] = new \App\Form\UserInscritFormType();
    }
}
