<?php

namespace ContainerJoSgotS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssociationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AssociationType' shared autowired service.
     *
     * @return \App\Form\AssociationType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AssociationType'] = new \App\Form\AssociationType();
    }
}
