<?php

namespace ContainerJoSgotS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogPostFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BlogPostFormType' shared autowired service.
     *
     * @return \App\Form\BlogPostFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\BlogPostFormType'] = new \App\Form\BlogPostFormType(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
