<?php

namespace ContainerJoSgotS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewTopicTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\NewTopicType' shared autowired service.
     *
     * @return \App\Form\NewTopicType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\NewTopicType'] = new \App\Form\NewTopicType();
    }
}
