<?php

namespace ContainerJoSgotS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpportuniteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OpportuniteController' shared autowired service.
     *
     * @return \App\Controller\OpportuniteController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\OpportuniteController'] = $instance = new \App\Controller\OpportuniteController();

        $instance->setContainer(($container->privates['.service_locator.vM_XwGp'] ?? $container->load('get_ServiceLocator_VMXwGpService'))->withContext('App\\Controller\\OpportuniteController', $container));

        return $instance;
    }
}
