<?php

namespace ContainerJoSgotS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldPostFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\OldPostFormType' shared autowired service.
     *
     * @return \App\Form\OldPostFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\OldPostFormType'] = new \App\Form\OldPostFormType();
    }
}
