<?php

namespace ContainerJoSgotS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParamsUserControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ParamsUserController' shared autowired service.
     *
     * @return \App\Controller\ParamsUserController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ParamsUserController'] = $instance = new \App\Controller\ParamsUserController(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\RoleRepository'] ?? $container->load('getRoleRepositoryService')), ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.vM_XwGp'] ?? $container->load('get_ServiceLocator_VMXwGpService'))->withContext('App\\Controller\\ParamsUserController', $container));

        return $instance;
    }
}
