<?php

namespace ContainerS221VZR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BlogController' shared autowired service.
     *
     * @return \App\Controller\BlogController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'BaseController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'BlogController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'UploadHelper.php';

        $container->services['App\\Controller\\BlogController'] = $instance = new \App\Controller\BlogController(($container->privates['App\\Repository\\BlogPostRepository'] ?? $container->load('getBlogPostRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\HistoriqueRepository'] ?? $container->load('getHistoriqueRepositoryService')), ($container->privates['App\\Services\\UploadHelper'] ?? ($container->privates['App\\Services\\UploadHelper'] = new \App\Services\UploadHelper((\dirname(__DIR__, 4).'/public/images')))));

        $instance->setContainer(($container->privates['.service_locator.TqNo1sD'] ?? $container->load('get_ServiceLocator_TqNo1sDService'))->withContext('App\\Controller\\BlogController', $container));

        return $instance;
    }
}
