<?php

namespace ContainerS221VZR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogPostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wGOyHbk.App\Entity\BlogPost' shared service.
     *
     * @return \App\Entity\BlogPost
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wGOyHbk": it references class "App\\Entity\\BlogPost" but no such service exists.');
    }
}
