<?php

namespace ContainerS221VZR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserFunctionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IxBlXdo.App\Service\UserFunctions' shared service.
     *
     * @return \App\Service\UserFunctions
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.IxBlXdo": it references class "App\\Service\\UserFunctions" but no such service exists.');
    }
}
