<?php

namespace ContainerDgpDyCi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IxBlXdoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IxBlXdo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IxBlXdo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'topic' => ['privates', '.errored..service_locator.IxBlXdo.App\\Entity\\Topic', NULL, 'Cannot autowire service ".service_locator.IxBlXdo": it references class "App\\Entity\\Topic" but no such service exists.'],
            'topicRepository' => ['privates', 'App\\Repository\\TopicRepository', 'getTopicRepositoryService', true],
            'userFunctions' => ['privates', '.errored..service_locator.IxBlXdo.App\\Service\\UserFunctions', NULL, 'Cannot autowire service ".service_locator.IxBlXdo": it references class "App\\Service\\UserFunctions" but no such service exists.'],
        ], [
            'manager' => '?',
            'topic' => 'App\\Entity\\Topic',
            'topicRepository' => 'App\\Repository\\TopicRepository',
            'userFunctions' => 'App\\Service\\UserFunctions',
        ]);
    }
}
