<?php

namespace ContainerDgpDyCi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6FSKsKcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6FSKsKc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6FSKsKc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'association' => ['privates', '.errored..service_locator.6FSKsKc.App\\Entity\\Association', NULL, 'Cannot autowire service ".service_locator.6FSKsKc": it references class "App\\Entity\\Association" but no such service exists.'],
            'associationRepository' => ['privates', 'App\\Repository\\AssociationRepository', 'getAssociationRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'opportuniteRepository' => ['privates', 'App\\Repository\\OpportuniteRepository', 'getOpportuniteRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.6FSKsKc.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.6FSKsKc": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'association' => 'App\\Entity\\Association',
            'associationRepository' => 'App\\Repository\\AssociationRepository',
            'manager' => '?',
            'opportuniteRepository' => 'App\\Repository\\OpportuniteRepository',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
