<?php

namespace ContainerDgpDyCi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoriqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ThC0.Xw.App\Entity\Historique' shared service.
     *
     * @return \App\Entity\Historique
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ThC0.Xw": it references class "App\\Entity\\Historique" but no such service exists.');
    }
}
