<?php

namespace ContainerDgpDyCi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldPostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hdra02_.App\Entity\OldPost' shared service.
     *
     * @return \App\Entity\OldPost
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hdra02_": it references class "App\\Entity\\OldPost" but no such service exists.');
    }
}
