<?php

namespace ContainerKpyGxxw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ThC0_XwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ThC0.Xw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ThC0.Xw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'historique' => ['privates', '.errored..service_locator.ThC0.Xw.App\\Entity\\Historique', NULL, 'Cannot autowire service ".service_locator.ThC0.Xw": it references class "App\\Entity\\Historique" but no such service exists.'],
        ], [
            'historique' => 'App\\Entity\\Historique',
        ]);
    }
}
