<?php

namespace ContainerKpyGxxw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WGOyHbkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wGOyHbk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wGOyHbk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blogPost' => ['privates', '.errored..service_locator.wGOyHbk.App\\Entity\\BlogPost', NULL, 'Cannot autowire service ".service_locator.wGOyHbk": it references class "App\\Entity\\BlogPost" but no such service exists.'],
        ], [
            'blogPost' => 'App\\Entity\\BlogPost',
        ]);
    }
}
