<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPfA5u7l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPfA5u7l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPfA5u7l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPfA5u7l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPfA5u7l\App_KernelDevDebugContainer([
    'container.build_hash' => 'PfA5u7l',
    'container.build_id' => 'a52783e1',
    'container.build_time' => 1618881745,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPfA5u7l');
