<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDgpDyCi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDgpDyCi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDgpDyCi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDgpDyCi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDgpDyCi\App_KernelDevDebugContainer([
    'container.build_hash' => 'DgpDyCi',
    'container.build_id' => 'ef3d2029',
    'container.build_time' => 1618952466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDgpDyCi');
