<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWzYpARn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWzYpARn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWzYpARn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWzYpARn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWzYpARn\App_KernelDevDebugContainer([
    'container.build_hash' => 'WzYpARn',
    'container.build_id' => 'e48c39a7',
    'container.build_time' => 1618502589,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWzYpARn');
